### ISSUE TITLE
issues for installation.html

### ISSUE THREAD

**Issue by chunhualiao** [HPC-FAIR/docs#1]
https://hpcfair.readthedocs.io/en/latest/0_index/installation.html
* what is editale ? Do you mean editable?   What does editable installation mean?
* Please state hardware and software requirements: what CPU, GPU, OS, Python versions etc are required?
*

**Comment by thelechen** [comment]
Thank you for catching the typo and the software requirements suggestion! They will be fixed within the next commit planed later today.

> What does editable installation mean?
Right now, the only way to install the HPCFAIR version of Transformers is to use the so-called editable installation. "Editable installation" with pip refers to the ability to install a Python package in a way that allows the user to modify the package's source code and see the changes we make within the HPCFAIR project reflected immediately without needing to re-install the package. The best option would be to release a package for installation, and we maintain the updates of the package. However, we need to discuss issues such as license, package host, etc., before releasing a package.

**Comment by thelechen** [comment]
@chunhualiao We have fixed this issue in the latest commit 56fa8c1
